"""Main Worker class for executing generated scripts."""

import logging
from pathlib import Path
from types import ModuleType
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn

from mega_ai.orchestrator.models import TaskConfig, TaskStatus
from mega_ai.orchestrator.task_manager import (
    get_task_path,
    load_task_config,
    update_task_status,
)
from mega_ai.worker.exceptions import (
    BackupError,
    ExecutionError,
    RollbackError,
    ScriptLoadError,
    TaskNotReadyError,
    WorkerError,
)
from mega_ai.worker.script_loader import (
    load_script,
    validate_backup_script,
    validate_runner_script,
)


class Worker:
    """
    Executes transformation scripts generated by the Orchestrator.

    This is a simple script executor, NOT an agentic loop.
    The AI is used by runner.py for data transformations.
    """

    def __init__(
        self,
        project_path: Path | None = None,
        console: Console | None = None,
    ):
        self.project_path = project_path or Path.cwd()
        self.console = console or Console()
        self.logger = logging.getLogger(__name__)

    def execute(self, task_uuid: str, dry_run: bool = False) -> bool:
        """
        Execute the runner.py script for a task.

        Args:
            task_uuid: The task UUID to execute
            dry_run: If True, preview changes without executing

        Returns:
            True if successful

        Raises:
            WorkerError: On various failure conditions
        """
        task_path = get_task_path(self.project_path, task_uuid)

        # Validate task exists
        if not task_path.exists():
            raise WorkerError(f"Task not found: {task_uuid}")

        # Load and validate task config
        config = load_task_config(task_path)
        self._validate_task_ready(config)

        # Display header
        self._print_header(config, dry_run)

        # Setup logging
        self._setup_file_logging(task_path)

        try:
            # Load scripts
            runner_path = task_path / "runner.py"
            backup_path = task_path / "backup.py"

            self.logger.info(f"Loading scripts from {task_path}")

            runner = load_script(runner_path, f"runner_{task_uuid}")
            validate_runner_script(runner)

            backup_module = load_script(backup_path, f"backup_{task_uuid}")
            validate_backup_script(backup_module)

            self.console.print("[green]Scripts loaded successfully[/green]")

            # Create backup (unless dry-run)
            if not dry_run:
                self._create_backup(task_path, config, backup_module)
            else:
                self.console.print("[dim]Skipping backup (dry-run mode)[/dim]")

            # Execute runner
            result = self._execute_runner(task_path, config, runner, dry_run)

            # Update status on success
            if not dry_run:
                update_task_status(task_path, TaskStatus.COMPLETED)

            self._print_success(config, dry_run, result)
            return True

        except ScriptLoadError as e:
            self.logger.error(f"Script load failed: {e}")
            update_task_status(task_path, TaskStatus.FAILED)
            raise

        except BackupError as e:
            self.logger.error(f"Backup failed: {e}")
            update_task_status(task_path, TaskStatus.FAILED)
            raise

        except ExecutionError as e:
            self.logger.error(f"Execution failed: {e}")
            update_task_status(task_path, TaskStatus.FAILED)
            self.console.print(
                f"\n[yellow]Tip: Run [cyan]mega-ai rollback {task_uuid}[/cyan] "
                "to restore from backup[/yellow]"
            )
            raise

        except Exception as e:
            self.logger.exception("Unexpected error")
            update_task_status(task_path, TaskStatus.FAILED)
            raise WorkerError(f"Worker failed: {e}") from e

    def rollback(self, task_uuid: str, backup_file: str | None = None) -> bool:
        """
        Rollback a task by restoring from backup.

        Args:
            task_uuid: The task UUID to rollback
            backup_file: Optional specific backup file to restore

        Returns:
            True if successful

        Raises:
            RollbackError: If rollback fails
        """
        task_path = get_task_path(self.project_path, task_uuid)

        if not task_path.exists():
            raise RollbackError(f"Task not found: {task_uuid}")

        config = load_task_config(task_path)

        self.console.print(
            Panel.fit(
                f"[bold yellow]Rolling Back Task[/bold yellow]\n"
                f"UUID: {task_uuid}\n"
                f"Description: {config.description}",
                border_style="yellow",
            )
        )

        # Setup logging
        self._setup_file_logging(task_path)

        try:
            # Load backup script
            backup_path = task_path / "backup.py"
            backup_module = load_script(backup_path, f"backup_{task_uuid}")
            validate_backup_script(backup_module)

            # Execute restore
            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=self.console,
            ) as progress:
                progress.add_task("Restoring from backup...", total=None)

                self.logger.info("Starting rollback")

                # Call restore function
                if backup_file:
                    backup_module.restore(backup_file=backup_file)
                else:
                    backup_module.restore()

                self.logger.info("Rollback completed")

            # Update status
            update_task_status(task_path, TaskStatus.ROLLED_BACK)

            self.console.print("\n[bold green]Rollback completed successfully![/bold green]")
            return True

        except ScriptLoadError as e:
            raise RollbackError(f"Cannot load backup script: {e}") from e

        except Exception as e:
            self.logger.exception("Rollback failed")
            raise RollbackError(f"Rollback failed: {e}") from e

    def _validate_task_ready(self, config: TaskConfig) -> None:
        """Ensure task is in a valid state for execution."""
        valid_statuses = {
            TaskStatus.READY,
            TaskStatus.FAILED,
            TaskStatus.COMPLETED,
            TaskStatus.ROLLED_BACK,
        }

        if config.status not in valid_statuses:
            raise TaskNotReadyError(
                f"Task status is '{config.status.value}', expected one of: "
                f"{[s.value for s in valid_statuses]}"
            )

    def _create_backup(
        self,
        task_path: Path,
        config: TaskConfig,
        backup_module: ModuleType,
    ) -> str:
        """Create a backup before executing transformation."""
        update_task_status(task_path, TaskStatus.BACKING_UP)

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=self.console,
        ) as progress:
            progress.add_task("Creating backup...", total=None)

            self.logger.info("Creating backup")

            try:
                backup_file: str = backup_module.backup()
                self.logger.info(f"Backup created: {backup_file}")
            except Exception as e:
                raise BackupError(f"Backup failed: {e}") from e

        self.console.print("[green]Backup created[/green]")
        return backup_file

    def _execute_runner(
        self,
        task_path: Path,
        config: TaskConfig,
        runner: ModuleType,
        dry_run: bool,
    ) -> dict[str, Any] | None:
        """Execute the runner.py script."""
        update_task_status(task_path, TaskStatus.EXECUTING)

        mode_text = "[cyan](DRY RUN)[/cyan] " if dry_run else ""
        self.console.print(f"\n{mode_text}[bold]Executing transformation...[/bold]")

        self.logger.info(f"Starting execution (dry_run={dry_run})")

        try:
            # Call runner with dry_run parameter
            result: dict[str, Any] | None = runner.run(dry_run=dry_run)

            self.logger.info("Execution completed")
            return result

        except Exception as e:
            raise ExecutionError(f"Execution failed: {e}") from e

    def _print_header(self, config: TaskConfig, dry_run: bool) -> None:
        """Print execution header."""
        mode = "[DRY RUN] " if dry_run else ""
        self.console.print(
            Panel.fit(
                f"[bold blue]{mode}MEGA-AI Worker[/bold blue]\n"
                f"UUID: {config.uuid}\n"
                f"Task: {config.description}",
                border_style="blue",
            )
        )

        # Show target info if available
        if config.target.table:
            self.console.print(f"\n[dim]Target: {config.target.table}")
            if config.target.rows_count:
                self.console.print(f"Rows: {config.target.rows_count:,}[/dim]")

    def _print_success(
        self, config: TaskConfig, dry_run: bool, result: dict[str, Any] | None
    ) -> None:
        """Print success message."""
        if dry_run:
            self.console.print(
                "\n[bold cyan]Dry run completed![/bold cyan]\n"
                f"To execute for real: [cyan]mega-ai worker {config.uuid}[/cyan]"
            )
        else:
            self.console.print("\n[bold green]Task completed successfully![/bold green]")

        # Show result summary if available
        if result and isinstance(result, dict):
            if "rows_processed" in result:
                self.console.print(f"[dim]Rows processed: {result['rows_processed']}[/dim]")
            if "summary" in result:
                self.console.print(f"[dim]{result['summary']}[/dim]")

    def _setup_file_logging(self, task_path: Path) -> None:
        """Setup logging to file in task folder."""
        log_file = task_path / "logs" / "worker.log"
        log_file.parent.mkdir(exist_ok=True)

        # Avoid adding duplicate handlers
        for handler in self.logger.handlers[:]:
            if isinstance(handler, logging.FileHandler):
                self.logger.removeHandler(handler)

        handler = logging.FileHandler(log_file)
        handler.setLevel(logging.DEBUG)
        handler.setFormatter(logging.Formatter("%(asctime)s - %(levelname)s - %(message)s"))
        self.logger.addHandler(handler)
        self.logger.setLevel(logging.DEBUG)
